version: '3'

services:
  database:
    build:
      context: mysql
      dockerfile: Dockerfile.prod
    image: joaogabrieldlb/mysql:prod
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql/volume:/var/lib/mysql
    networks:
      - default-network

  nodejs:
    build:
      context: nodejs
      dockerfile: Dockerfile.prod
    image: joaogabrieldlb/nodejs:prod
    container_name: nodejs
    restart: always
    tty: true
    networks:
      - default-network
    depends_on:
      - database

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    image: joaogabrieldlb/nginx:prod
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
    networks:
      - default-network
    depends_on:
      - nodejs
    ports:
      - "8080:80"

networks:
  default-network:
    driver: bridge